### ISSUE TITLE
jk lol

### ISSUE THREAD

**Issue by cheuble** [TheKingy34/arm11loaderhax#3]
CIA build when?

**Comment by Kingy34** [comment]
when 11.2 gets a downgrader.
So, never.

**Comment by Kingy34** [comment]
oh, and make it yourself >:^(

**Comment by Kingy34** [comment]
Fixed in [this release](https://github.com/TheKingy34/arm11loaderhax/releases/tag/141171A). Closing.

**Comment by cheuble** [comment]
👌

**Comment by Kingy34** [comment]
🚯

**Comment by Xtheman166** [comment]
> when 11.2 gets a downgrader.
https://gbatemp.net/threads/safehax-11-1-2-downgrade-without-dsiware.455456/
:^)

**Comment by Xtheman166** [comment]
"when 11.2 gets a downgrader.
So, never."
https://gbatemp.net/threads/safehax-11-1-2-downgrade-without-dsiware.455456/
:^)
