### ISSUE TITLE
DISCONTINUED????????????

### ISSUE THREAD

**Issue by KevinX8** [TheKingy34/arm11loaderhax#7]
I was playing some pc gaems using this amazing homebrew when I saw it said DISCONTINUED???
Can I still play pc gaems and boot any kernals after support it dropped?

**Comment by Kingy34** [comment]
haha no sir, the a11lh is not discontinued sir, arm11build (a shitty bootloader) is discontinued sir sir.

**Comment by KevinX8** [comment]
oh good good, so I expect 64 bit support to come soon? Also possible to download ram with latest build? 128mb is not cutting it for me anymore, I tried to play morrowind and it just killed my 3ds

**Comment by Kingy34** [comment]
go to http://www.downloadmoreram.com on your web browser and you should be good to go.

**Comment by KevinX8** [comment]
thank you sir, 3ds support the 32GB ram download?
